export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        ink: {
          DEFAULT: '#0F1B2D',
          2: '#16273F',
          3: '#1E3355',
          900: '#0F1B2D',
          800: '#16273F', 
          700: '#1E3355',
        },
        seal: { DEFAULT: '#B8863B', dark: '#8C6526', bg: '#FBF3E4' },
        sealGold: '#F2D9AE',
        paper: '#F6F4EE',
        surface: '#FFFFFF',
        border: { DEFAULT: '#E5E1D3', 2: '#DAD5C4' },
        bodyText: { DEFAULT: '#1C2430', muted: '#6C7280', faint: '#9CA0A8' },
        danger: { DEFAULT: '#B0362A', bg: '#FBEAE7' },
        success: { DEFAULT: '#1F7A4D', bg: '#E6F4EC' },
        warning: { DEFAULT: '#B4650B', bg: '#FCF0DA' },
        info: { DEFAULT: '#2E5F82', bg: '#E8F1F6' },
        violet: { DEFAULT: '#5B4B8A', bg: '#EFEBF7' },
        'table-header': '#FBFAF6',
        'row-hover': '#FBFAF3',
        'sidebar-text': '#C6CDD9',
        'sidebar-title': '#7C8698',
        'sidebar-hover': 'rgba(255,255,255,.06)',
        'sidebar-active-bg': 'rgba(184,134,59,.18)',
      },
      fontFamily: {
        display: ['Fraunces', 'IBM Plex Sans', 'serif'],
        ui: ['IBM Plex Sans', '-apple-system', 'sans-serif'],
        mono: ['IBM Plex Mono', 'monospace'],
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '10px',
        lg: '16px',
        pill: '20px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(15,27,45,.06)',
        DEFAULT: '0 4px 16px rgba(15,27,45,.08)',
        lg: '0 12px 40px rgba(15,27,45,.16)',
      },
      fontSize: {
        'badge': ['11px', { fontWeight: '600' }],
        'nav': ['13px', { fontWeight: '500' }],
        'nav-section': ['10px', { letterSpacing: '0.09em' }],
        'crumb': ['12.5px', {}],
        'table-header': ['11px', { letterSpacing: '0.05em', textTransform: 'uppercase' }],
        'table-cell': ['13px', {}],
        'stat-value': ['26px', { lineHeight: '1' }],
        'page-title': ['24px', { letterSpacing: '-0.2px' }],
      },
      spacing: {
        'sidebar': '230px',
        'topbar': '60px',
      },
    },
  },
  plugins: [],
};
